### ISSUE TITLE
Cant get it to run

### ISSUE THREAD

**Issue by MachoPanko** [PanasonicConnect/rap#7]
![image](https://github.com/user-attachments/assets/d374aad1-8cda-459b-a05b-da3886ed96dd)
Dear Authors, Im very interested in your work and would like to do some development around it, but the set up is really vague and i keep getting this error,
Basically what i have done is ,
1) git clone alfworld repo and downloaded everything, i am successfully able to ```alfworld-play-tw```
2) git clone rap to the same repo, and move main.py , prompts, Openapi-api.txt  into alfworld folder. 
3) then i try python3 main.py  
and i guess based on my output RAP is not running.

Can you help me out? really interested in this.
I am running on WSL with GPU, python3.12.5

**Comment by tomoyukik0** [comment]
Hi, thank you for your interest in our work.
The error mentioned above is likely caused by the inability to load ALFWorld's games, as indicated by the "0 games" message.
To resolve this, please refer to the following page and check the settings of the ALFWORLD_DATA path and ensure that alfworld-download has been executed. This might help improve the situation.
https://github.com/alfworld/alfworld
